config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :tasks 
  root 'tasks#index'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:task_comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    #  @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_url, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Not Authorised" if @task.nil?
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :deadline, :complete, :file, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_comment %>
    <%= form.text_field :task_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Task comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.task_comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task comment:</strong>
  <%= @comment.task_comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Task Managment App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
     
        <li class="nav-item">
        <i class="bi bi-check-lg"></i>
          <%= link_to '<i class="fas fa-check"></i>'.html_safe, tasks_path, class:"nav-link active" %> 
       
        </li>
        
        <% if user_signed_in? %>

          <li class="nav-item">
          <%= link_to 'New Tasks', new_task_path, class:"nav-link active" %> 
          </li>

          <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link active" %> 
          </li>

          <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %> 
          </li>

        <% else %>

          <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %> 
          </li>
          
          <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link active" %> 
          </li>

        <% end %>  

      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Task Managment System</title>


  </head>
  <body>
  
    <%= render 'home/header' %>
    
    <div class="container">
      <%= yield %>
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/866cfc098f.js" crossorigin="anonymous"></script>

    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&amp;display=swap'>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.standalone.min.css'><link rel="stylesheet" href="./style.css">
    

    <script>
    window.onload = function () {
    bootlint.showLintReportForCurrentDocument([], {
        hasProblems: false,
        problemFree: false
    });

    $('[data-toggle="tooltip"]').tooltip();

    function formatDate(date) {
        return (
            date.getDate() +
            "/" +
            (date.getMonth() + 1) +
            "/" +
            date.getFullYear()
        );
    }

    var currentDate = formatDate(new Date());

    $(".due-date-button").datepicker({
        format: "dd/mm/yyyy",
        autoclose: true,
        todayHighlight: true,
        startDate: currentDate,
        orientation: "bottom right"
    });

    $(".due-date-button").on("click", function (event) {
        $(".due-date-button")
            .datepicker("show")
            .on("changeDate", function (dateChangeEvent) {
                $(".due-date-button").datepicker("hide");
                $(".due-date-label").text(formatDate(dateChangeEvent.date));
            });
    });
};
    </script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_name %>
    <%= form.text_field :task_name %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <span class= "fa fa-calendar my-2 px-1 text-primary"></span> 
    <%= form.date_field :deadline %>
  </div>

  <div class="field">
    <%= form.label :complete %>
    <%= form.check_box :complete %>
  </div> 

  <div class="field">
  <%= form.label :file %>
  <%= form.file_field :file %>
</div> 

  <div class="field">
    <%= form.number_field :user_id, id: :task_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <p id="notice"><%= notice %></p>

  <h1>Tasks</h1>

  <table class="table table-bordered">
  <!-- <thead>
      <tr>
        <th colspan="1" >Complete</th>  
        <th colspan="10">Task name</th>
        <th>Deadline</th> 
        <th colspan="1"></th>
      </tr>
    </thead>
  -->
    <tbody>
      <% @tasks.each do |task| %>

        <% if task.user == current_user %>
          <% if task.complete %>
            <tr class="table-secondary">
              <td colspan="1"> 
                <center>
                  <%= form_for(task) do |f| %>
                    <%= f.text_field :task_name, type: 'hidden' %>
                    <%= f.check_box :complete, :checked => false, :style => 'visibility: hidden' %>
                    <%= f.submit "  ", class:"btn btn-success btn-sm" %>
                  <% end %>
                </center>
              </td>
              <!-- <td><%= task.complete %></td>  -->
              <td colspan="10"><%= link_to task.task_name, task_path(task)  %></td>
              
              <!-- <td><%= task.deadline %></td> -->
              <td colspan="1"><%= link_to 'X', task, class:"btn btn-outline-danger btn-sm",method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% else %>
              <tr>
              <td colspan="1">
                <center>
                  <%= form_for(task) do |f| %>
                    <%= f.text_field :task_name, type: 'hidden' %>
                    <%= f.check_box :complete, :checked => true, :style => 'visibility: hidden' %>
                    <%= f.submit "  ", class:"btn btn-secondary btn-sm" %>
                  <% end %>
                </center>
              </td>
              <!-- <td><%= task.complete %></td>  -->
              <td colspan="10"><%= link_to task.task_name, task_path(task) %></td>
            
              <!-- <td><%= task.deadline %></td> -->
              <td colspan="1"><%= link_to 'X', task, class:"btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>

<br>
  <br>

  <h1> WelCome to Task Managment System </h1>
  <h2>Please Sign in to continue </h2>

<% end %>

<!-- # <%= link_to 'New Task', new_task_path %> -->

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Task name:</strong>
  <%= @task.task_name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>


<p>
  <strong>Preview:</strong>
</p>
<p>
  <%= image_tag (@task.file) %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', root_path %>